#!/bin/bash

# 显示部署命令

clear

echo "╔════════════════════════════════════════════════════════╗"
echo "║                                                        ║"
echo "║     🚀 AI Studio Platform - 一键部署                   ║"
echo "║                                                        ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo ""
echo "📋 请在终端中复制并执行以下命令："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd /Users/lujiaheng/Documents/ai-studio-platform && bash one-click-deploy.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo ""
echo "📝 部署步骤预览："
echo ""
echo "  1️⃣  Vercel登录（浏览器自动打开）"
echo "  2️⃣  回答几个问题（都有默认值）"
echo "  3️⃣  等待2-3分钟部署"
echo "  4️⃣  获取公网地址！"
echo ""
echo ""
echo "💡 提示："
echo ""
echo "  • 登录时选择 GitHub（推荐）或 Email"
echo "  • 问题都可以直接按回车使用默认值"
echo "  • 部署完成后会显示公网地址"
echo ""
echo ""
echo "🎉 3分钟后您的网站将上线！"
echo ""
